### PR TITLE
corrected sentence in hindi and sanskrit

### PR DESCRIPTION
**Pull request by TheShubhendra**
# Hindi
`मैं तुमसे प्यार करता` is totally wrong sentence , the right is `मैं तुमसे प्यार करता हूँ`

# Sanskrit
***त्वयि स्निह्यामि*** in sanskrit means `Love you` not `I love you`
'I' -> `अहं` so `I love you` = `अहं त्वयि स्निह्यामि`

### CODE REVIEW

**Comment by TheShubhendra** [comment]
@IonicaBizau Is  anything wrong with my commits?

**Comment by IonicaBizau** [comment]
@praveenscience @prem1835 Can you please review this pull request?

**Comment by prem1835** [comment]
@IonicaBizau this pull request is right.
I love you = मैं तुमसे प्यार करता हूँ
The Sanskrit one is already right but what this commit suggest is also have same meaning.

**Comment by praveenscience** [comment]
@IonicaBizau Can we ask Suresh? I don't know Hindi. I'll check as well, with my friends too... 😁

**Comment by TheShubhendra** [comment]
> @IonicaBizau this pull request is right.
> I love you = मैं तुमसे प्यार करता हूँ
> The Sanskrit one is already right but what this commit suggest is also have same meaning.

`त्वयि स्निह्यामि` means `Love you` not `I love you` . 
So right are both but  `अहं त्वयि स्निह्यामि` is better.

**Pull request merged**
